#!/usr/bin/env python

from random import sample 

def issorted(lst,n):
    n = n - 1
    while n > 0:
        if lst[n - 1] > lst[n]:
            return False
        n -= 1
    return True

def bogosort(lst):
    n = len(lst)
    while not issorted(lst,n):
        lst = sample(lst,n)
    return lst

seed = 10
lst = sample(range(seed),seed)
print(bogosort(lst))
