#!/usr/bin/env python

# Sorting algorithms

from random import sample

def bubble(lst):
    print('Bubble Sort')
    p = 0
    n = len(lst) - 1
    while p < n:
        for i in range(n - p):
            if lst[i + 1] < lst[i]:
                tmp = lst[i+1]
                lst[i+1] = lst[i]
                lst[i] = tmp
        p += 1
    return lst

lst = sample(range(100),100) 

print("Unsorted List\n",lst,"\n")
print(bubble(lst),"\n")
