#!/usr/bin/env python

# Cocktail sort

from random import sample

def cocktail(lst):
    n = len(lst) - 1    # Maior índíce da lista
    for p in range(0,n//2):
        for i in range(p, n - p):
            if lst[i+1] < lst[i]:
                tmp = lst[i+1]
                lst[i+1] = lst[i]
                lst[i] = tmp
        
        for j in range(n - p, p, -1):
            if lst[j-1] > lst[j]:
                tmp = lst[j-1]
                lst[j-1] = lst[j]
                lst[j] = tmp
    return lst

lst = sample(range(0,100),100)
#lst = [4,1,5,10,21,2,10,3,12,6,9]

print(cocktail(lst))
