#!/usr/bin/env python

from random import sample 

def insert(lst):
    print('Insertion Sort')
    n = len(lst)
    for i in range(1,n):
        pvt = lst[i]
        p = i
        while p >= 1 and pvt < lst[p-1]:
            lst[p] = lst[p-1]
            p -= 1
        lst[p] = pvt
    return lst

cnt = 10000
lst = sample(range(cnt),cnt)

#print("Unsorted List\n",lst,"\n")
print("Sorted:\n",insert(lst))
