#!/usr/bin/env python 

# Selection Sort 

from random import sample 

def selection(lst):

    n = len(lst)
    for i in range(0, n - 1):
        tmp = lst[i]
        for j in range(i + 1, n):
            if lst[j] < tmp:
                idx = j
                tmp = lst[j]

        lst[idx] = lst[i]
        lst[i] = tmp
    
    return lst

lst = sample(range(0,200),200)
print(selection(lst))

