#!/usr/bin/env python 

from random import sample

def shellsort(lst):
    n = len(lst)
    h = n//2

    while h > 0:
        for i in range(0,h):
            if lst[i] > lst[i+h]:
                tmp = lst[i+h]
                lst[i+h] = lst[i]
                lst[i] = tmp
        h = h//2
    
    for j in range(1,n):
        tmp = lst[j]
        k = j
        while k > 0 and tmp < lst[k-1]:
            lst[k] = lst[k-1]
            k -= 1
        lst[k] = tmp

    return lst

cnt = 10000
lst = sample(range(cnt),cnt)

#shellsort(lst)
#print(lst)
print(shellsort(lst))
