#!/usr/bin/env python 

from random import sample

def shellsort(lst):
    n = len(lst)
    h = n//2
    while h > 0:
        i = h
        while i < n:
            j = i
            tmp = lst[i]
            while j >= h and tmp < lst[j-h]:
                lst[j] = lst[j-h]
                j = j - h
            lst[j] = tmp
            i += 1
        h = h//2
    return lst


cnt = 10000
lst = sample(range(cnt),cnt)

#shellsort(lst)
#print(lst)
print(shellsort(lst))
